"""The generator version stamp.

The golden comparison deliberately normalizes this stamp away (see
``tests.util.VERSION_TOKEN``), so without these tests a bump could silently stop
reaching the output and nothing would notice.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from util import compile_rdl, export_str, strip_version  # noqa: E402

from peakrdl_pss.__about__ import __version__  # noqa: E402


def test_package_header_carries_the_real_version(tmp_path):
    text = export_str(compile_rdl("basic"), tmp_path)
    assert "Generated by peakrdl-pss %s -- do not edit." % __version__ in text


def test_sidecar_generator_carries_the_real_version(tmp_path):
    sidecar = tmp_path / "basic.sidecar.json"
    export_str(compile_rdl("basic"), tmp_path, sidecar_path=str(sidecar))
    payload = json.loads(sidecar.read_text())
    assert payload["generator"] == "peakrdl-pss %s" % __version__


def test_strip_version_only_touches_the_stamp():
    """The normalization must not rewrite a version-shaped value elsewhere."""
    text = "peakrdl-pss %s\nreset = %s;\n" % (__version__, __version__)
    assert strip_version(text) == "peakrdl-pss <version>\nreset = %s;\n" % __version__
